/**
 * Type definitions for Traycer-mini
 * A simplified AI-powered code generation workflow tool
 */

/**
 * Represents a structured plan for a coding task
 */
export interface Plan {
  /** Description of the coding task */
  taskName: string;
  /** Array of actionable coding steps */
  steps: string[];
  /** List of file paths to be created/modified */
  filesToModify: string[];
  /** ISO timestamp of when the plan was created */
  createdAt: string;
  /** Unique identifier (e.g., slugified task name + timestamp) */
  id: string;
  /** Rationale for why each file needs changing */
  rationale?: string;
  /** Files in order they should be generated (dependency ordering) */
  dependencyOrder?: string[];
  /** Captured context at plan time */
  contextSnapshot?: {
    projectSummary: string;
    existingPatterns: {
      importStyle: string;
      namingConvention: string;
      testFramework: string;
    };
  };
}

/**
 * Represents a code proposal generated by AI
 */
export interface CodeProposal {
  /** Target file path relative to project root */
  filePath: string;
  /** Unified diff format showing changes */
  diff: string;
  /** Complete new file content */
  newContent: string;
  /** Whether file is new or existing */
  operation: 'create' | 'modify';
  /** ISO timestamp of when the proposal was created */
  createdAt: string;
}

/**
 * Represents a staged code proposal with approval status
 * Extends CodeProposal with additional metadata
 */
export interface StagedProposal extends CodeProposal {
  /** Unique proposal identifier */
  id: string;
  /** Reference to originating plan */
  planId: string;
  /** Approval status */
  approved: boolean;
  /** History of rejections with reasons */
  rejectionHistory?: Array<{
    reason: string;
    timestamp: string;
  }>;
  /** Which files were used as context during generation */
  generationContext?: string[];
  /** AI's own assessment of the generated code */
  aiReviewSummary?: string;
}

/**
 * Supported AI providers
 */
export type AIProvider = 'openai' | 'anthropic' | 'google' | 'groq';

/**
 * Configuration for AI code generation
 */
export interface GeneratorConfig {
  /** AI provider to use */
  provider: AIProvider;
  /** API key for the provider */
  apiKey: string;
  /** Model name to use */
  model: string;
  /** Temperature for generation (default 0.3) */
  temperature: number;
}

/**
 * Result of code verification checks
 */
export interface VerificationResult {
  /** Whether verification passed (no errors) */
  success: boolean;
  /** Compilation/lint errors found */
  errors: string[];
  /** Warnings found (non-blocking) */
  warnings: string[];
}